export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
export const REFRESH_JWT_TOKEN = 'REFRESH_JWT_TOKEN';
export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED';
export const SIGN_IN_API_REQUEST = 'SIGN_IN_API_REQUEST';
export const SIGN_IN_SUCCEEDED = 'SIGN_IN_SUCCEEDED';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const AppUser_INFO = 'AppUser_INFO';
export const Load_User_INFO = 'Load_User_INFO';

export const GET_ADVERTISEMENT_LIST = 'GET_ADVERTISEMENT_LIST';
export const SET_ADVERTISEMENT_LIST = 'SET_ADVERTISEMENT_LIST';
export const LOAD_STUDENT_INFO = 'LOAD_STUDENT_INFO';
export const STUDENT_INFO = 'STUDENT_INFO';

export const USER_SIGN_ON = 'USER_SIGN_ON';
export const SIGN_ON_SUCCEEDED = 'SIGN_ON_SUCCEEDED';
export const SIGN_ON_FAILED = 'SIGN_ON_FAILED';
export const GET_ADVERTISEMENT_BYID = 'GET_ADVERTISEMENT_BYID';
